### ISSUE TITLE
tuneup check: null reference error

### ISSUE THREAD

**Issue by seaneagan** [google/tuneup.dart#30]
```
$ pub global activate tuneup
Resolving dependencies...
+ analyzer 0.25.0+1
+ args 0.13.0
+ cli_util 0.0.1+1
+ collection 1.1.0
+ path 1.3.5
+ source_span 1.1.2
+ stack_trace 1.3.1
+ string_scanner 0.1.3+1
+ tuneup 0.0.5+4
+ watcher 0.9.5
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.2
Downloading tuneup 0.0.5+4...
Downloading yaml 2.1.2...
Downloading analyzer 0.25.0+1...
Downloading args 0.13.0...
Precompiling executables...
Loading source assets...
Precompiled tuneup:tuneup.
Activated tuneup 0.0.5+4.
Installed executable tuneup.

$ tuneup check
Checking project unscripted...
Unhandled exception:
AnalysisException: <rethrow>
Caused by The null object does not have a setter 'evaluationResult='.

NoSuchMethodError: method not found: 'evaluationResult='
Receiver: null
Arguments: [Instance of 'EvaluationResultImpl']
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6434)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413)
#4      AnalysisContextImpl.computeErrors (package:analyzer/src/generated/engine.dart:1605)
#5      CheckCommand.execute (package:tuneup/src/check_command.dart:63)
#6      Tuneup.processArgs (package:tuneup/tuneup.dart:117)
#7      main (http://localhost:55191/tuneup.dart:14)
#8      _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#9      _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

Caused by The null object does not have a setter 'evaluationResult='.

NoSuchMethodError: method not found: 'evaluationResult='
Receiver: null
Arguments: [Instance of 'EvaluationResultImpl']
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      ConstantValueComputer._computeValueFor (package:analyzer/src/generated/constant.dart:692)
#2      ConstantValueComputer.computeValues (package:analyzer/src/generated/constant.dart:558)
#3      LibraryResolver._performConstantEvaluation.<anonymous closure> (package:analyzer/src/generated/resolver.dart:8458)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150)
#5      LibraryResolver._performConstantEvaluation (package:analyzer/src/generated/resolver.dart:8441)
#6      LibraryResolver.resolveLibrary (package:analyzer/src/generated/resolver.dart:7911)
#7      ResolveDartLibraryTask.internalPerform (package:analyzer/src/generated/engine.dart:10538)
#8      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6430)
#9      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403)
#10     AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804)
#11     AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413)
#12     AnalysisContextImpl.computeErrors (package:analyzer/src/generated/engine.dart:1605)
#13     CheckCommand.execute (package:tuneup/src/check_command.dart:63)
#14     Tuneup.processArgs (package:tuneup/tuneup.dart:117)
#15     main (http://localhost:55191/tuneup.dart:14)
#16     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#17     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)


#0      AnalysisContextImpl.recordResolveDartLibraryTaskResults (package:analyzer/src/generated/engine.dart:2496)
#1      AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask (package:analyzer/src/generated/engine.dart:4866)
#2      ResolveDartLibraryTask.accept (package:analyzer/src/generated/engine.dart:10530)
#3      AnalysisTask.perform.<anonymous closure> (package:analyzer/src/generated/engine.dart:6411)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150)
#5      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6411)
#6      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804)
#7      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413)
#8      AnalysisContextImpl.computeErrors (package:analyzer/src/generated/engine.dart:1605)
#9      CheckCommand.execute (package:tuneup/src/check_command.dart:63)
#10     Tuneup.processArgs (package:tuneup/tuneup.dart:117)
#11     main (http://localhost:55191/tuneup.dart:14)
#12     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#13     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
```

**Comment by devoncarew** [comment]
https://github.com/google/tuneup.dart/commit/2a4155c0259f6d301e676bc167002a8500df241d

Can you re-test?

**Comment by seaneagan** [comment]
```
$ pub global activate tuneup
Package tuneup is currently active at version 0.0.5+4.
Resolving dependencies...
+ analyzer 0.24.6 (0.25.0+1 available)
+ args 0.12.2+6 (0.13.0 available)
+ cli_util 0.0.1+1
+ collection 1.1.0
+ path 1.3.5
+ source_span 1.1.2
+ stack_trace 1.3.1
+ string_scanner 0.1.3+1
+ tuneup 0.0.5+5
+ watcher 0.9.5
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.2
Downloading tuneup 0.0.5+5...
Precompiling executables...
Loading source assets...
Precompiled tuneup:tuneup.
Activated tuneup 0.0.5+5.
Installed executable tuneup.

$ tuneup.bat check
Checking project unscripted...
Unhandled exception:
AnalysisException: <rethrow>
Caused by The null object does not have a setter 'evaluationResult='.

NoSuchMethodError: method not found: 'evaluationResult='
...
```

**Comment by devoncarew** [comment]
`version 0.0.5+4` ==> I deployed version 0.0.5+5 w/ a slightly older version of the analyzer. You _should_ get it locally. On a CI system like travis, I think there's some fancy caching which means that very new pub packages are just not visible for a few hours.

**Comment by seaneagan** [comment]
See above:
`Downloading tuneup 0.0.5+5...`
`analyzer 0.24.6 (0.25.0+1 available)`

**Comment by seaneagan** [comment]
This was just an analyzer bug:

https://code.google.com/p/dart/issues/detail?id=23354

**Comment by devoncarew** [comment]
We'll need to rev to a new analyzer version to capture the fix -
